version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11.8-alpine
    expose:
      - "5432"
    ports:
    - "5432:5432"
    volumes:
    - data-volume:/data/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assessments-db
    networks:
    - postgres
volumes:
  data-volume:
networks:
  postgres:
    driver: bridge
